---
include:
  - board: nice_nano/nrf52840/zmk
    shield: sofle_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: sofle_left-nice_nano_v2-zmk
  - board: nice_nano/nrf52840/zmk
    shield: sofle_right
    artifact-name: sofle_right-nice_nano_v2-zmk
  - board: nice_nano/nrf52840/zmk
    shield: settings_reset
    artifact-name: settings_reset-nice_nano_v2-zmk
