# RGB underglow (no LEDs on this board)
CONFIG_ZMK_RGB_UNDERGLOW=n

# Encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Display — nice!view with nv gems custom screen
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# ZMK Studio
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO=y



# Bluetooth TX power
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# nice!view gem animation (disable to save battery)
CONFIG_NICE_VIEW_GEM_ANIMATION=n
