# Encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# ZMK Studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# Power management — deep sleep is the single biggest battery saver
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=15000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000